# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20170324_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Sum')),
                ('date', models.DateField(default=datetime.date.today, verbose_name=b'Date')),
            ],
        ),
    ]
